---
title: "Skill intensity over years"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Skill intensity over years}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(VNFirmSurvey)
library(data.table)
library(ggplot2)
library(DataExplorer)
```


```{r}
data("skill_07_dta")
data("skill_01_dta")

dta_list <- list(skill_07_dta, skill_01_dta)

stacked_data <- rbindlist(dta_list)
```



```{r plot-skill}
stacked_data$svyear <- as.factor(stacked_data$svyear)

ggplot(stacked_data, aes(x = SI_1, col = svyear)) + 
  geom_density()

ggplot(stacked_data, aes(x = SI_2, col = svyear)) + 
  geom_density()

ggplot(stacked_data, aes(x = SI_3, col = svyear)) + 
  geom_density()
```


# Wage Data 

```{r load-data}
data("wage_dta")
```


Let's take a first look at the data

```{r first-look}
plot_intro(wage_dta)

```

## Missing variables
If I use ld13 for 2001, I have more than 3000 missing observations for total labor while only 8 for ldc11. 

Furthermore, 9.6% of the firms in 2001 miss total compensation data, while only 0.12% miss data 

```{r missing-variable}
plot_missing(wage_dta)
profile_missing(wage_dta)
```



```{r solve-missing}
wage_dta_na_free <- na.omit(wage_dta)

wage_dta_na_free <- wage_dta_na_free[total_L > 0]
plot_missing(wage_dta_na_free)
```





## Update features 
```{r features}
update_columns(wage_dta, c("tinh", "madn", "macs", "ma_thue"), as.factor)

```


## Distributions
```{r continuous}
plot_histogram(wage_dta_na_free)

summary(wage_dta_na_free)
```

## Correlation
```{r heat-map}
plot_correlation(wage_dta_na_free, maxcat = 5L)

```

## Can I link plants to firms?

```{r}
library(haven)
cn2007 <- (read_dta("/Volumes/GoogleDrive/My Drive/econ_datasets/Vietnam_VES/Data/Stata_2007_2009/Stata_2007/cn2007.dta"))  ## Maybe phieu 3.3 chi phi 

festive_exp <- (read_dta("/Volumes/GoogleDrive/My Drive/econ_datasets/Vietnam_VES/Data/Stata_2007_2009/Stata_2007/ds2007.dta", 
                         encoding="latin1"))  
names(festive_exp)


setDT(festive_exp)

festive_exp[!duplicated(macs), .(tinh, macs) ,by = .(madn)][order(madn)]

## What does it mean to have duplicated macs? Does it mean 2 plants belonging to the same firm? 

View(head(festive_exp))

```


