---
title: "Skill intensity over years"
output: bookdown::pdf_document2 
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(VNFirmSurvey)
library(data.table)
library(ggplot2)
library(DataExplorer)
library(here)
library(haven)
library(labelled)
library(dplyr)
library(labelled)
```

```{r load-data}

dta_list <- list(here("inst", "extdata", 
                    "Stata_2001", 
                    "dn2001.dta"), 
                 here("inst", "extdata", 
                    "Stata_2004", 
                    "dn2004.dta"),
                 here("inst", "extdata", 
                    "Stata_2007", 
                    "dn2007.dta") )

years <- c(2001, 2004, 2007)

```




## Location 

The location codes at district level change from 2004. I need a concodore between these two system 
```{r}

location_dta <- getLocation(dta_list)

location_dta[svyear == 2001, .(madn, xa, huyen, tinh)]

location_dta[svyear == 2007 & tinh == "01"
             & huyen == "001", .(madn, xa, huyen, tinh)]

```

## Ownership 
```{r load-ownership}
ownership_dta <- ownership(dta_list)
```

```{r}
ggplot(ownership_dta[, .N, by = .(svyear, simple_ownership)],
       aes(fill=simple_ownership, y=N, x=svyear)) + 
    geom_bar(position="fill", stat="identity") + 
  theme_classic()

```


## Entry, exit 
```{r}
dynamic_dta <- EntryExit(dta_list, base_year = years)
```


# Industry code
For 2010, use nganh_kd and nganh_cu to create a cocondorance. 
Use nganh_kd as the main product code. 
```{r}

 # geo_dta[[1]][, .(nganh_kd)]
 #      geo_dta[[3]][, .(nganh_kd, nganh_cu)]
 #      names(geo_dta[[3]])
```




# Plant 
```{r}
# festive_exp <- (read_dta("/Volumes/GoogleDrive/My Drive/econ_datasets/Vietnam_VES/Data/Stata_2011/cs2011.dta", encoding = "latin1")) 

```



# Wage Data

```{r load-wage-data}

wage_dta <- getWage(dta_list)
```


```{r wage-distribution}
graph_wage <- merge(wage_dta[, .(svyear, wage_bill_USD)],
                    wage_dta[, .(mean_wage = mean(wage_bill_USD)), 
                       by = svyear], 
                    by = "svyear")

ggplot(graph_wage, aes(x = log(wage_bill_USD), col = factor(svyear))) + 
  geom_density()



```
